# Generated by Django 5.2.7 on 2025-10-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhaar_no', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('eligibility_rules', models.JSONField(blank=True, default=dict, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('official_link', models.URLField(blank=True, null=True)),
                ('benefit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Schemes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCategories',
            fields=[
                ('user_cat_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'UserCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserEligibility',
            fields=[
                ('eligibility_id', models.AutoField(primary_key=True, serialize=False)),
                ('eligibility_status', models.CharField(choices=[('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User_Eligibility',
                'managed': False,
            },
        ),
    ]
