# Generated by Django 5.2.7 on 2025-10-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251003_1915'),
    ]

    operations = [
    ]
