# Generated by Django 5.2.7 on 2025-10-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleEngine',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('min_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pension_status', models.BooleanField(blank=True, null=True)),
                ('disability_cert', models.BooleanField(blank=True, null=True)),
                ('unemployment_status', models.BooleanField(blank=True, null=True)),
                ('education_required', models.CharField(blank=True, max_length=100, null=True)),
                ('business_turnover_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'Rule_Engine',
                'managed': False,
            },
        ),
    ]