# Generated by Django 5.2.7 on 2026-02-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ruleengine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('grievance_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('raised_on', models.DateTimeField(auto_now_add=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Grievances',
                'managed': False,
            },
        ),
    ]
